swagger: "2.0"
info:
  version: "0.0.1"
  title: Express Api
# during dev, should point to your local machine
host: localhost:3000
# basePath prefixes all resource paths 
basePath: /api/v1
# 
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json

paths:
  # register here all paths
  $ref: "./paths/authorization.yaml"
  $ref#cars: "./paths/cars.yaml"
  $ref#images: "./paths/images.yaml"

  /swagger:
    x-swagger-pipe: swagger_raw



# complex objects have schema definitions
definitions:
  # register here all definitions
  $ref#User: "./models/User.yaml"
  # sasas
  $ref#general: "./request-models/general.yaml"
